home/urls.py
from django.urls import path

from home import views

urlpatterns=[
    path('', views.HomeTemplateView.as_view(), name='homepage')
]

products/urls.py
from django.urls import path

from products import views

urlpatterns = [
    path('list_trainers/', views.TrainerListView.as_view(), name='list-trainers'),
    path('list_products/', views.ProductListView.as_view(), name='list-products'),
    path('cart/', views.cart_view, name='cart'),
    path('add_to_card/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout_view, name='checkout_view'),
    path('subscriptions/', views.SubscriptionTemplateView.as_view(), name='subscriptions'),
    path('contact/', views.ContactCreateView.as_view(), name='contact'),

]

strongcore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from userextend.forms import AuthenticationNewForm
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('userextend.urls')),

    path("accounts/login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userextend/urls.py
from django.urls import path

from userextend import views

urlpatterns = [
    path('create_user/', views.UserCreateView.as_view(), name='create-user'),]

home/models.py
from django.db import models

# Create your models here.

products/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


class SiteUser(AbstractUser):
    def __str__(self):
        return self.last_name + " " + self.first_name


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='static/', null=True, blank=True)

    def __str__(self):
        return self.name


class Trainer(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    photo = models.ImageField(upload_to='static/', null=True, blank=True)
    price_1_session = models.CharField(max_length=255)
    price_5_session = models.CharField(max_length=255)
    price_10_session = models.CharField(max_length=255)


    def __str__(self):
        return self.name


class Cart(models.Model):
    STATUS = [
        ('open', 'Open'),
        ('closed', 'Closed'),
    ]
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS, default='open')



class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)


class Appointment(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    duration = models.DurationField(default=datetime.timedelta(hours=1))

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=255)
    message = models.TextField()

userextend/models.py
from django.db import models

# Create your models here.

userextend/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from products.models import SiteUser


class AuthenticationNewForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your username'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your password'})


class UserForm(UserCreationForm):
    class Meta:
        model = SiteUser
        fields =[
        #   'first_name',
        #    'last_name',
             'email',
             'username'
                ]



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Please enter your email'})
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Please enter your username'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Please enter your password'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Please enter your password confirmation'})

home/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

class HomeTemplateView(TemplateView):
    template_name = 'home/homepage.html' # specificam calea fisierului .html pe care o dorim randata/afisata.

products/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView

from products.models import Trainer, Product, Cart, CartItem, Contact
from strongcore import settings


class TrainerListView(LoginRequiredMixin, ListView):
    template_name = 'trainer/list_trainers.html'
    model = Trainer
    context_object_name = 'trainers'

    def get_queryset(self):
        return Trainer.objects.all()


class ProductListView(LoginRequiredMixin, ListView):
    template_name = 'products/list_products.html'
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all()

class SubscriptionTemplateView(TemplateView):
    template_name = 'subscriptions/subscriptions.html'


@login_required
def cart_view(request):
    cart = get_open_cart(request)
    return render(request, 'cart.html', {'cart': cart})


@login_required
def get_open_cart(request):
    user = request.user
    open_cart, created = Cart.objects.get_or_create(status='open', user=user)
    return open_cart


@login_required
def add_to_cart(request):
    if request.method == "POST":
        product_id = request.POST.get('product_id', Product.objects.first().id)
        quantity = request.POST.get('quantity', 1)
        cart = get_open_cart(request)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product_id=product_id)
        cart_item.quantity += int(quantity)
        if cart_item.quantity > 0:
            cart_item.save()
        else:
            cart_item.delete()
    return redirect(request.META.get('HTTP_REFERER', reverse_lazy('cart')))

class ContactCreateView(CreateView):
    model = Contact
    template_name = 'home/homepage.html'
    fields = '__all__'
    success_url = reverse_lazy('homepage')

def checkout_view(request):
    open_cart = get_open_cart(request)
    open_cart.status = 'closed'
    open_cart.save()
    send_mail(subject='subiect', message='mesaj', from_email=settings.EMAIL_HOST_USER , recipient_list=[settings.EMAIL_HOST_USER,open_cart.user.email], fail_silently=False)
    return redirect(request.META.get('HTTP_REFERER'))

userextend/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import CreateView

from random import randint

from products.models import SiteUser
from userextend.forms import UserForm


class UserCreateView(CreateView):
    template_name = 'userextend/create_user.html'
    model = SiteUser
    form_class = UserForm
    success_url = reverse_lazy('login')

    # def form_valid(self, form):
    #     if form.is_valid():
    #         new_user = form.save(commit=False)
    #         new_user.save()
    #         return redirect(self.success_url)
    #     return super().form_valid(form)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

{% include 'navbar.html' %}


{% block content %} {% endblock %}


</body>
</html>

templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %} {% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'subscriptions' %}">Abonamente</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'list-trainers' %}">Antrenori</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'list-products' %}">Produse</a>
                </li>
            <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
             <a class="navbar-brand" href="{% url 'cart' %}"><img src="{% static 'assets/img/card-logo-white.jpg' %}" alt="..."/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
                 {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary">Logout, {{ user.username }}</button>
                </form>
            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
                    <a href="{% url 'create-user' %}" class="btn btn-outline-secondary">Sign up</a>
                </div>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %} {% endblock %}
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base2.html' %}
{% load static %}
{% block title %} Cart


{% endblock %}

{% block content %}

    <header class="masthead" xmlns:padding="http://www.w3.org/1999/xhtml"
            xmlns:padding-left="http://www.w3.org/1999/xhtml">
        <div class="container">
            <div class="masthead-subheading">Cosul Tau De Cumparaturi</div>
            <div class="masthead-heading text-uppercase">Toate Produsele Sunt Listate Mai Jos</div>
        </div>
    </header>

    <div class="container">
        <div class="row mt-10">
            {#        <div class="col-md-6">#}
            {% for cart_item in cart.cartitem_set.all %}
                <div class="col-md-7">
                    <div class="row mt-6">
                        <div class="card border border-dark">
                            {#                        <img src="{{ cart_item.product.photo.url }}" class="card-img-top" alt="imagine_profil"#}
                            {#                             height="450"#}
                            {#                             style="object-fit: cover">#}
                            <div class="card-body">
                                <h5 class="card-title">{{ cart_item.product.name }}</h5>
                                <p class="card-text">Pret: {{ cart_item.product.price }}</p>
                                <p class="card-text">Quantity: {{ cart_item.quantity }}</p>
                                <form action="{% url 'add_to_cart' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ cart_item.product.id }}">
                                    <input type="hidden" name="quantity" value="-{{ cart_item.quantity }}">
                                    <button type="submit" class="btn btn-primary">Remove Item</button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                
                <div class="col-md-4">
                    <img src="{% static 'assets/img/empty_cart.png' %}" alt="..." height="800" width="800" />
                </div>
            {% endfor %}
        
{#         {% for cart_item in cart.cartitem_set.all %}#}
{#             total = o#}
{#             total += cart_item.price#}
{#        {% endfor %}#}
        
        
            {#        </div>#}
        </div>
    </div>
    <div class="container"  style="padding-top: 50px;
  padding-bottom: 20px;
  padding-left: 30px;
  padding-right: 40px;">
    
       
    <form action="{% url 'checkout_view' %}" method="post">
                                {% csrf_token %}
     <button type="submit" class="btn btn-primary btn-lg">Cumpara!</button>
    </form>
    </div> 
   

    {#    <h1>Shopping Cart</h1>#}
    {#    <ul>#}
    {#        {% for cart_item in cart_items %}#}
    {#            <li>{{ cart_item.item.name }} - ${{ cart_item.item.price }} (Quantity: {{ cart_item.quantity }})</li>#}
    {#        {% endfor %}#}
    {#    </ul>#}


    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Contacteaza-ne</h2>
                <h3 class="section-subheading text-muted"></h3>
            </div>

            <form id="contactForm" method="post" action="{% url 'contact' %}">
                {% csrf_token %}
                <div class="row align-items-stretch mb-5">
                    <div class="col-md-6">
                        <div class="form-group">
                            <!-- Name input-->
                            <input class="form-control" id="name" name="name" type="text" placeholder="Nume *"
                                  />
                            <div class="invalid-feedback">A name is required.</div>
                        </div>
                        <div class="form-group">
                            <!-- Email address input-->
                            <input class="form-control" id="email" name="email" type="email" placeholder="Email *"
                                  />
                            <div class="invalid-feedback">An email is required.</div>
                            <div class="invalid-feedback">Email is not valid.</div>
                        </div>
                        <div class="form-group mb-md-0">
                            <!-- Phone number input-->
                            <input class="form-control" id="phone" type="tel" name="phone_number" placeholder="Numar de Telefon *"
                                 />
                            <div class="invalid-feedback">A phone number is
                                required.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-textarea mb-md-0">
                            <!-- Message input-->
                            <textarea class="form-control" id="message" placeholder="Mesajul *" name="message"
                                    ></textarea>
                            <div class="invalid-feedback">A message is required.
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Submit success message-->
                <!---->
                <!-- This is what your users will see when the form-->
                <!-- has successfully submitted-->
                <div class="d-none" id="submitSuccessMessage">
                    <div class="text-center text-white mb-3">
                        <div class="fw-bolder">Form submission successful!</div>
                    </div>
                </div>
                <!-- Submit error message-->
                <!---->
                <!-- This is what your users will see when there is-->
                <!-- an error submitting the form-->
                <div class="d-none" id="submitErrorMessage">
                    <div class="text-center text-danger mb-3">Error sending message!</div>
                </div>
                <!-- Submit Button-->
                <div class="text-center">
                    <button class="btn btn-primary btn-xl text-uppercase" id="" type="submit">Send
                        Message
                    </button>
                </div>
            </form>
        </div>
    </section>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2023</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="https://twitter.com" aria-label="Twitter" target="_blank"><i
                            class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com" aria-label="Facebook" target="_blank"><i
                            class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com" aria-label="LinkedIn" target="_blank"><i
                            class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Simplu</title>
</head>
<body style="font-family: Arial, sans-serif;">

    <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px;">
        <h2 style="color: #333;">Subiectul Emailului</h2>
        <p>Salut, {{ user.name }}</p>
        <p>Comanda dumneavoastra a fost plasata cu succes </p>
        <p>  Comanda contine:</p>
        {% for cart_item in cart.cartitem_set.all %}
            <p>{{ cart_item.product}} x {{ cart_item.quantity }} </p>
        
        {% endfor %}
        <p>Va multumim mult pentru comanda!</p>
        <p>Cu drag,</p>
        <p>StrongCore</p>
    </div>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'list-trainers' %}">Antrenori</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Abonamente</a>
      </li>
    
           <li class="nav-item">
        <a class="nav-link" href="{% url 'list-products' %}">Produse</a>
      </li>
        {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary">Logout, {{ user.username }}</button>
                </form>
            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
                    <a href="{% url 'create-user' %}" class="btn btn-outline-secondary">Sign up</a>
                </div>
            {% endif %}
        
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
          <li class="nav-item">
        <a class="nav-link" href="#">Cos Cumparaturi</a>
      </li>
      </li>
    </ul>
  </div>
</nav>
    

templates/products/list_products.html
{% extends 'base2.html' %}
{% load static %}
{% block title %} Produse {% endblock %}

{% block content %}

    <!-- Masthead-->
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Cele mai bune produse din Romania</div>
            <div class="masthead-heading text-uppercase">Suplimente Online</div>
        </div>
    </header>
    <div class="container">
        <div class="row mt-4">

            {% for product in products %}

                <div class="col-md-4">
                    <div class="card border border-dark">
                        <img src="{{ product.photo.url }}" class="card-img-top" alt="imagine_profil"
                             height="450"
                             style="object-fit: cover">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">Desciere: {{ product.description }}</p>
                            <p class="card-text">Pret: {{ product.price }}</p>
                            <p class="card-text">Email: {{ product.category }}</p>
                            <form action="{% url 'add_to_cart' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ product.id }}">
                                <input type="number" name="quantity" value="1">
                                <button type="submit" class="btn btn-primary">Buy Now</button>
                            </form>
                        </div>
                    </div>
                </div>


            {% endfor %}
        </div>
    </div>
    <!-- Contact-->
    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Contacteaza-ne</h2>
                <h3 class="section-subheading text-muted"></h3>
            </div>

            <form id="contactForm" method="post" action="{% url 'contact' %}">
                {% csrf_token %}
                <div class="row align-items-stretch mb-5">
                    <div class="col-md-6">
                        <div class="form-group">
                            <!-- Name input-->
                            <input class="form-control" id="name" name="name" type="text" placeholder="Nume *"
                                  />
                            <div class="invalid-feedback">A name is required.</div>
                        </div>
                        <div class="form-group">
                            <!-- Email address input-->
                            <input class="form-control" id="email" name="email" type="email" placeholder="Email *"
                                  />
                            <div class="invalid-feedback">An email is required.</div>
                            <div class="invalid-feedback">Email is not valid.</div>
                        </div>
                        <div class="form-group mb-md-0">
                            <!-- Phone number input-->
                            <input class="form-control" id="phone" type="tel" name="phone_number" placeholder="Numar de Telefon *"
                                 />
                            <div class="invalid-feedback">A phone number is
                                required.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-textarea mb-md-0">
                            <!-- Message input-->
                            <textarea class="form-control" id="message" placeholder="Mesajul *" name="message"
                                    ></textarea>
                            <div class="invalid-feedback">A message is required.
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Submit success message-->
                <!---->
                <!-- This is what your users will see when the form-->
                <!-- has successfully submitted-->
                <div class="d-none" id="submitSuccessMessage">
                    <div class="text-center text-white mb-3">
                        <div class="fw-bolder">Form submission successful!</div>
                    </div>
                </div>
                <!-- Submit error message-->
                <!---->
                <!-- This is what your users will see when there is-->
                <!-- an error submitting the form-->
                <div class="d-none" id="submitErrorMessage">
                    <div class="text-center text-danger mb-3">Error sending message!</div>
                </div>
                <!-- Submit Button-->
                <div class="text-center">
                    <button class="btn btn-primary btn-xl text-uppercase" id="" type="submit">Send
                        Message
                    </button>
                </div>
            </form>
        </div>
    </section>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2023</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="https://twitter.com" aria-label="Twitter" target="_blank"><i
                            class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com" aria-label="Facebook" target="_blank"><i
                            class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com" aria-label="LinkedIn" target="_blank"><i
                            class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

templates/userextend/create_user.html
{% extends 'base2.html' %}
{% block title %}Create a new User{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new User</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                          {#                csrf_token securizeaza impotriva anumitor tipuri de atacuri, e un tag Django ce trebuie folosit in formulare:#}
                        {% csrf_token %}
                        <div class="card-body">

                               {#                form e variabila Django trimisa pe baza unui model(Student)#}
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}